apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.environment }}-app"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.environment }}-app"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.environment }}-app"
  template:
    metadata:
      labels:
        app: "{{ .Values.environment }}-app"
    spec:
      containers:
        - name: "{{ .Values.environment }}-container"
          image: "{{ .Values.image }}"
          resources:
            requests:
              cpu: "{{ .Values.resources.requests.cpu }}"
              memory: "{{ .Values.resources.requests.memory }}"
            limits:
              cpu: "{{ .Values.resources.limits.cpu }}"
              memory: "{{ .Values.resources.limits.memory }}"
