apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.environment }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.environment }}-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
